###
generated by base-domain generator
###

BaseDomainLoopback = require('../../base-domain-loopback')
###*
repository of player

@class PlayerRepository
@extends LoopbackUserRepository
###
class PlayerRepository extends BaseDomainLoopback.LoopbackUserRepository

    @lbDefinitions:
        ttl    : 24 * 3600 * 365 * 10
        maxTTL : 24 * 3600 * 365 * 100

    @aclType: 'owner'

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'player'

module.exports = PlayerRepository
