###
generated by base-domain generator
###



BaseDomainLoopback = require('../../base-domain-loopback')

###*
repository of song

@class SongRepository
@extends LoopbackRelationRepository
###
class SongRepository extends BaseDomainLoopback.LoopbackRelationRepository
    @aclType: 'owner'
    @belongsTo: 'author'

    ###*
    model name to create

    @property modelName
    @static
    @protected
    @type String
    ###
    @modelName: 'song'

module.exports = SongRepository
